const CONST = {
    ZERO: 0,
    OUTPUT_COLUMN_NUMBER_0: 0,
    OUTPUT_COLUMN_NUMBER_1: 1,
    OUTPUT_COLUMN_NUMBER_2: 2,
    OUTPUT_COLUMN_NUMBER_3: 3,
    OUTPUT_COLUMN_NUMBER_4: 4,
    INDEX_OF_COLUMN_IN_INPUT_BODY: 1,
    INDEX_OF_COLUMN_IN_INPUT_FROM_NAME: 2,
    INDEX_OF_COLUMN_IN_INPUT_CATEGORIES: 15,
    CAM: 'CAM',
    CAM1: 'CAM1',
    CAM2: 'CAM2',
    CAM3: 'CAM3',
    CAM4: 'CAM4',
    CAM5: 'CAM5',
    CAM6: 'CAM6',
    CAM7: 'CAM7',
}

module.exports = CONST;